image: docker-compose:1.24.1

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:stable-dind

build:
  stage: build
  tags:
    - docker
  script:
    - sh build-base-images.sh
    - sh prod.sh build

