image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:stable-dind

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose

build:
  stage: build
  tags:
    - docker
  script:
    - sh build-base-images.sh
    - sh prod.sh build

