image:
  name: docker/compose:1.24.1
  entrypoint: [""]

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:19.03.1-dind

before_script:
  - docker-compose version
  - docker info

build:
  stage: build
  tags:
    - docker
  script:
    - sh build-base-images.sh
    - sh prod.sh build

