version: "3"
services:
  nginx:
    build:
      context: ../
      dockerfile: infrastructure/nginx.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../statamic:/var/www/statamic-site/
  fpm:
    build:
      context: ../
      dockerfile: infrastructure/statamic.Dockerfile
    volumes:
      - ../statamic:/var/www/statamic-site/
  node:
    build:
      context: ../
      dockerfile: infrastructure/node-dev.Dockerfile
    volumes:
      - ../statamic/site/themes/dufresnes/:/app/
      # A hack to avoid mounting the node_modules directory
      # https://stackoverflow.com/questions/29181032/
      - /app/node_modules/
