version: "3"
services:
  nginx:
    build:
      context: ../
      dockerfile: infrastructure/nginx.Dockerfile
    ports:
      - "8000:8000"
  fpm:
    build:
      context: ../
      dockerfile: infrastructure/statamic.Dockerfile
