version: "3"
services:
  nginx:
    build:
      context: ../
      dockerfile: infrastructure/nginx-dev.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../statamic:/var/www/statamic-site/
  fpm:
    build:
      context: ../
      dockerfile: infrastructure/fpm-dev.Dockerfile
    volumes:
      - ../statamic:/var/www/statamic-site/
